# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYRp5A8vlBWn8ihuZc0euT1kenfManZ6
"""

# EAI Assignment - Optimized SVM

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import random

# Dataset link (UCI): https://archive.ics.uci.edu/ml/datasets/wine+quality
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
data = pd.read_csv(url, sep=";")

print("Dataset Shape:", data.shape)
print(data.head())

# Step 2: Basic Data Analytics
# -----------------------------
print("\nData Description:\n", data.describe())
print("\nClass Distribution:\n", data['quality'].value_counts())

# Features & Target
X = data.drop("quality", axis=1)
y = data["quality"]

# Step 3: Define SVM Optimization Function
# -----------------------------
def optimize_svm(X_train, y_train, X_test, y_test, iterations=100):
    kernels = ["linear", "rbf", "poly", "sigmoid"]
    best_acc = 0
    best_params = None
    acc_list = []

    for i in range(iterations):
        kernel = random.choice(kernels)
        C = 10 ** random.uniform(-2, 2)   # penalty parameter
        gamma = 10 ** random.uniform(-2, 2)

        model = SVC(kernel=kernel, C=C, gamma=gamma)
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        acc = accuracy_score(y_test, preds)
        acc_list.append(acc)

        if acc > best_acc:
            best_acc = acc
            best_params = (kernel, C, gamma)

    return best_acc, best_params, acc_list

# Step 4: Run for 10 Samples

results = []
convergence_dict = {}

for s in range(1, 11):  # S1 to S10
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=s
    )
    best_acc, best_params, acc_list = optimize_svm(X_train, y_train, X_test, y_test)
    results.append([f"S{s}", best_acc, best_params])
    convergence_dict[f"S{s}"] = acc_list
    print(f"Sample {s}: Best Acc = {best_acc:.4f}, Params = {best_params}")


# Step 5: Store Results in Table

results_df = pd.DataFrame(results, columns=["Sample", "Best Accuracy", "Best Parameters"])
print("\nFinal Results:\n", results_df)


# Step 6: Convergence Graph for Best Sample

best_sample = results_df.loc[results_df["Best Accuracy"].idxmax(), "Sample"]
best_curve = convergence_dict[best_sample]

plt.figure(figsize=(8,5))
plt.plot(best_curve, label=f"Convergence - {best_sample}")
plt.xlabel("Iteration")
plt.ylabel("Accuracy")
plt.title("Convergence Graph of Best SVM")
plt.legend()
plt.show()